### ISSUE TITLE
Potential error when using convertID function 

### ISSUE THREAD

**Issue by Maberuiz** [LotharukpongJS/phylomapr#6]
When using convert ID it is possible that the biomartr search doesn’t have any results (result_BM has 0 rows) the function returns an error:

`Error in 'dplyr::inner_join()':`
`! Can't join 'x$ensembl_peptide_id' with 'y$ensembl_peptide_id' due to incompatible types.`
`ℹ 'x$ensembl_peptide_id' is a <character>.`
`ℹ 'y$ensembl_peptide_id' is a <logical>.`
`Run 'rlang::last_trace()' to see where the error occurred.`

I think it would be nice to change the function so that when this case happens a message is returned stating that the biomartr search did not have any results, rather than the error.

**Comment by LotharukpongJS** [comment]
Dear @Maberuiz ,

Thanks for pointing this out. I will have a look at this.

Best,
Sodai

**Comment by LotharukpongJS** [comment]
Hi again, would it be possible for you to show me an example script to reproduce this error?

**Comment by Maberuiz** [comment]
The following script will get as output the mentioned error. It is a non-sense example as I am just introducing the wrong ID name as filters but it shows clearly the behavior I was trying to explain. 

[Example_error_convertID.txt](https://github.com/LotharukpongJS/phylomapr/files/12928698/Example_error_convertID.txt)
